name: Build admin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/actions-setup@v2
        with:
          version: 8
      - run: |
          cd admin
          npm run build
